name: simple-mpc-devel
channels:
- conda-forge
dependencies:
- assimp[version='>=5.4.3,<5.4.4.0a0']
- benchmark
- bullet
- ccache
- cmake
- colcon-common-extensions
- compilers
- cxx-compiler
- eigen
- fmt
- ipython
- libboost-python[version='>=1.86.0,<1.87.0a0']
- libboost-python-devel
- libgcc[version='>=13']
- libstdcxx[version='>=13']
- matplotlib
- numpy[version='>=1.26.4,<2.0a0']
- octomap[version='>=1.9.8,<1.10.0a0']
- proxsuite
- python[version='>=3.12,<3.13.0a0']
- python_abi=3.12[build=*_cp312]
- qhull[version='>=2020.2,<2020.3.0a0']
- qhull-static
- scipy
- tracy
- urdfdom
- vcstool