[project]
name = "simple-mpc"
version = "0.1"
channels = ["conda-forge"]
description = "MPC schemes for locomotion"
platforms = ["linux-64", "osx-arm64"]
license = "BSD-2-Clause"
license-file = "LICENSE"
readme = "README.md"

[build-dependencies]
ccache = ">=4.9.1"
cmake = ">=3.10"
cxx-compiler = ">=1.7.0"
ninja = ">=1.11"

[dependencies]
python = ">=3"
eigenpy = ">=3.9.0"
pinocchio = ">=3,<4"
aligator = ">=0.16"
proxsuite = ">=0.7"
benchmark = ">=1.8.0"
tsid = ">=1.9.0,<2"
pybullet = ">=3"

[tasks]
clean = { cmd = "rm -rf build" }

[tasks.configure]
args = [{ "arg" = "buildtype", "default" = "Release" }, { "arg" = "buildtests", "default" = "OFF" }, { "arg" = "buildbenchmarks", "default" = "OFF" }]
cmd = "cmake -G Ninja -B build -S . -DCMAKE_BUILD_TYPE={{buildtype}} -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DBUILD_TESTING={{buildtests}} -DBUILD_BENCHMARK={{buildbenchmarks}} -DGENERATE_PYTHON_STUBS=ON -DCMAKE_CXX_COMPILER_LAUNCHER=ccache"

[tasks.build]
args = [{ "arg" = "buildtype", "default" = "Release" }, { "arg" = "buildtests", "default" = "OFF" }, { "arg" = "buildbenchmarks", "default" = "OFF" }]
cmd = "cmake --build build --target all"
depends-on = [{"task" = "configure", "args" = [{"buildtype" = "{{buildtype}}" }, {"buildtests" = "{{buildtests}}" }, {"buildbenchmarks" = "{{buildbenchmarks}}" }] }]

[tasks.install]
args = [{ "arg" = "buildtype", "default" = "Release" }, { "arg" = "buildtests", "default" = "OFF" }, { "arg" = "buildbenchmarks", "default" = "OFF" }]
cmd = "cmake --build build --target install"
depends-on = [{"task" = "build", "args" = [{"buildtype" = "{{buildtype}}" }, {"buildtests" = "{{buildtests}}" }, {"buildbenchmarks" = "{{buildbenchmarks}}" }] }]

[tasks.test]
args = [{ "arg" = "buildtype", "default" = "Debug" }]
cmd = "ctest --test-dir build --output-on-failure"
depends-on = [{"task" = "build", "args" = [{ "buildtype" = "{{buildtype}}" }, {"buildtests" = "ON"}] }]

[tasks.benchmark]
cmd = "cmake --build build --target run-benchmarks"
depends-on = [{"task" = "build", "args" = [{ "buildtype" = "Release" }, {"buildbenchmarks" = "ON"}] }]

[feature.lint]
dependencies = { pre-commit = ">=3.6.2" }
tasks = { lint = { cmd = "pre-commit run --all" } }

[environments]
lint = { features = ["lint"]}
