name: CI - OSX/Linux via Pixi

on:
  push:
    paths-ignore:
      - 'doc/**'
      - '.gitignore'
      - '*.md'
      - 'CHANGELOG.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  simple-mpc-pixi:
    name: ${{ matrix.os }} - ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    env:
      CCACHE_BASEDIR: "${GITHUB_WORKSPACE}"
      CCACHE_DIR: "${GITHUB_WORKSPACE}/.ccache"
      CCACHE_COMPRESS: true
      CCACHE_COMPRESSLEVEL: 6

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        build_type: [Release, Debug]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: actions/cache@v4
      with:
        path: .ccache
        key: ccache-macos-linux-pixi-${{ matrix.os }}-${{ matrix.build_type }}-${{ github.sha }}
        restore-keys: ccache-macos-linux-pixi-${{ matrix.os }}-${{ matrix.build_type }}-

    - uses: prefix-dev/setup-pixi@v0.9.1
      with:
        pixi-version: v0.56.0
        cache: true

    - name: Build simple-mpc
      shell: bash -l {0}
      env:
        CMAKE_BUILD_PARALLEL_LEVEL: 4
      run: |
        pixi run test ${{ matrix.build_type }}

  check:
    if: always()
    name: check-macos-linux-pixi

    needs:
    - simple-mpc-pixi

    runs-on: ubuntu-latest

    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
